version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: get-stdin
    versions:
    - 8.0.0
  - dependency-name: json5
    versions:
    - 2.1.3
